export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AUTH_NOT_INITIALIZED: "AUTH_NOT_INITIALIZED",
  AUTH_ALREADY_INITIALIZED: "AUTH_ALREADY_INITIALIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_LOCKED: "SESSION_LOCKED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  ROOT_PATH_INVALID: "ROOT_PATH_INVALID",
  ROOT_PATH_CONFLICT: "ROOT_PATH_CONFLICT",
  SCAN_TASK_NOT_FOUND: "SCAN_TASK_NOT_FOUND",
  SCAN_TASK_CONFLICT: "SCAN_TASK_CONFLICT",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
